name: Build

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Printing compiler info
        run: |
          echo $CC
          cc --version
      - name: Building source code
        run: |
         mkdir -p cmake_build && \
         cd ./cmake_build && \
         cmake .. && \
         make

